version: '3'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    env_file:
      - .env
    depends_on:
      - redis
      - jaeger
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      REDIS_HOST: redis
      JAEGER_HOST: jaeger
  redis:
    restart: always
    image: redis:5.0.7
    ports:
      - "6379:6379"
    volumes:
      - .data/db:/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "16686:16686"
